//? METADATA | [S.E.O] Search Engine Optimization
import type { Metadata } from "next";
//? GOOGLE FONTS & LOCAL FONTS | Optimized Fonts
import { roboto, nunito } from "./(custom)/fonts/google-fonts";
//? STYLESHEET | Global/Root
import "@/styles/scss/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-UK">
      <body
        className={`${roboto.variable} ${nunito.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
